@startuml

skinparam Padding 10

skinparam title {
  FontName "Bradley Hand"
  'FontSize 10
  BorderRoundCorner 15
  titleBorderThickness 2
  titleBorderColor red
  titleBackgroundColor Aqua-CadetBlue
}

skinparam caption {
  FontName "Bradley Hand"
}

skinparam interface {
  BackgroundColor #72BF43/white
  BorderColor black
  'FontColor
  FontName "Bradley Hand"
  'FontSize 150
  'FontStyle bold_italic
  StereotypeFontColor blue
  'StereotypeFontName
  'StereotypeFontSize 15
  'StereotypeFontStyle
  SequenceArrowThickness 120
}

skinparam component {
  ArrowFontName "Bradley Hand"
  ArrowColor #000000
  'ArrowFontColor #777777
  'ArrowFontSize 10
  ArrowFontStyle bold_italic
  'ArrowLollipopColor green
  ArrowThickness 3
  'ColorArrowSeparationSpace blue
  'SequenceArrowThickness 12
}

left header
<font color=red>Warning:</font>
Do not use in production.
endheader


right footer

Generated with PlantUML by Miguel Villafuerte
endfooter

@enduml
